GET http://localhost:3000/admin-api


###

post http://localhost:3000/api/register
Content-Type: application/json

{
    "userType":"user",
    "username":"bharat",
    "password":"bharat",
    "email":"bharat@gmail.com",
    "address":{
        "city":"vijayawada",
        "pincode":534300
    }
}
###
post http://localhost:3000/api/register
Content-Type: application/json


{
    "userType":"seller",
    "username":"kishore",
    "password":"kishore",
    "email":"kishore@gmail.com",
    "address":{
        "city":"rajahmundry",
        "pincode":534300
    }
}

###

post http://localhost:3000/api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"krishna",
    "password":"krishna"
}